// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSrcDir(arg1) {
  return window['go']['main']['App']['AddSrcDir'](arg1);
}

export function GetAlbums() {
  return window['go']['main']['App']['GetAlbums']();
}

export function GetArtists() {
  return window['go']['main']['App']['GetArtists']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetTracks() {
  return window['go']['main']['App']['GetTracks']();
}

export function RemoveSrcDir(arg1) {
  return window['go']['main']['App']['RemoveSrcDir'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
