// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {indexer} from '../models';

export function AddSrcDir(arg1:string):Promise<void>;

export function GetAlbums():Promise<Array<main.Group>>;

export function GetArtists():Promise<Array<main.Group>>;

export function GetConfig():Promise<config.Config>;

export function GetFolders():Promise<Array<main.Group>>;

export function GetTracks():Promise<Array<indexer.Track>>;

export function RemoveSrcDir(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;
