// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {indexer} from '../models';

export function AddSrcDir(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetTracks():Promise<Array<indexer.Track>>;

export function RemoveSrcDir(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;
